apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui-new
  namespace: longhorn-system-new
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-local-only@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn-new
    app.kubernetes.io/version: v1.10.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: longhorn-1.10.1
spec:
  ingressClassName: traefik
  rules:
  - host: longhorn-new.ga-nan.ovh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
  tls:
  - hosts:
    - longhorn-new.ga-nan.ovh
    secretName: longhorn-new-tls
