apiVersion: v1
kind: Service
metadata:
  name: longhorn-backend
  namespace: longhorn-system-new
  labels:
    app: longhorn-manager
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn-new
    app.kubernetes.io/version: v1.10.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: longhorn-1.10.1
spec:
  type: ClusterIP
  ports:
  - name: manager
    port: 9500
    protocol: TCP
    targetPort: manager
  selector:
    app: longhorn-manager
