apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui-local
  namespace: longhorn-system
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`longhorn.lan`)
    kind: Rule
    middlewares:
    - name: longhorn-admin-basicauth
    services:
    - name: longhorn-frontend
      port: 80
