apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui-local
  namespace: longhorn-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-longhorn-admin-basicauth@kubernetescrd
spec:
  ingressClassName: traefik-private
  rules:
  - host: longhorn.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
