apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-whitelist
  namespace: longhorn-system
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.18/32
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`longhorn.ga-nan.ovh`)
      kind: Rule
      middlewares:
        - name: longhorn-whitelist
          namespace: longhorn-system
      services:
        - name: longhorn-frontend
          port: 80