apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-settings
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.10.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: longhorn-1.10.1
data:
  # Default Longhorn settings
  backup-target: ""
  backup-target-credential-secret: ""
  allow-recurring-job-while-volume-detached: "false"
  create-default-disk-labeled-nodes: "true"
  default-data-path: "/var/lib/longhorn/"
  replica-soft-anti-affinity: "false"
  replica-auto-balance: "disabled"
  storage-over-provisioning-percentage: "100"
  storage-minimal-available-percentage: "25"
  storage-reserved-percentage-for-default-disk: "30"
  upgrade-checker: "true"
  default-replica-count: "2"
  default-data-locality: "disabled"