apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: vaultwarden-admin-restrict@vaultwarden
spec:
  ingressClassName: traefik-public
  tls:
  - hosts:
    - vaultwarden.ga-nan.ovh
    secretName: vaultwarden-tls
  rules:
  - host: vaultwarden.ga-nan.ovh
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: vaultwarden
            port:
              number: 80
