apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`vaultwarden.ga-nan.ovh`) && PathPrefix(`/admin`)
    kind: Rule
    priority: 100
    services:
    - name: vaultwarden
      port: 80
    middlewares:
    - name: vaultwarden-admin-basicauth
  tls:
    secretName: vaultwarden-tls
