apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-websocket
  namespace: vaultwarden
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: vaultwarden-headers@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    traefik.ingress.kubernetes.io/router.middlewares: vaultwarden-websocket-headers@kubernetescrd
spec:
  ingressClassName: traefik-public
  rules:
  - host: vaultwarden.ga-nan.ovh
    http:
      paths:
      - path: /notifications/hub
        pathType: Prefix
        backend:
          service:
            name: vaultwarden
            port:
              number: 80
  tls:
  - hosts:
    - vaultwarden.ga-nan.ovh
    secretName: vaultwarden-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vaultwarden-websocket-headers
  namespace: vaultwarden
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      Connection: "Upgrade"
      Upgrade: "websocket"
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowOriginList:
      - "https://vaultwarden.ga-nan.ovh"
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
