apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-public
  namespace: homeassistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik-public
  tls:
  - hosts:
    - ha.ga-nan.ovh
    secretName: homeassistant-tls
  rules:
  - host: ha.ga-nan.ovh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 80
