apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-acme-challenge
  namespace: homeassistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik-public
  rules:
  - host: ha.ga-nan.ovh
    http:
      paths:
      - path: /.well-known/acme-challenge
        pathType: Prefix
        backend:
          service:
            name: cm-acme-http-solver
            port:
              number: 8089
