apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-public
  namespace: homeassistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik-public
  # tls:
  # - hosts:
  #   - ha.ga-nan.ovh
  #   secretName: homeassistant-tls
  rules:
  - host: ha.ga-nan.ovh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 80
