apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-acme
  namespace: homeassistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: traefik-public
  rules:
  - host: ha.ga-nan.ovh
    http:
      paths:
      - path: /.well-known/acme-challenge
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 80
