apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-private
  namespace: traefik
spec:
  controller: traefik.io/ingress-controller
  parameters:
    apiGroup: traefik.io
    kind: IngressClassParams
    name: traefik-private-params
