apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=false
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`longhorn.lan`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80
    middlewares:
    - name: longhorn-ui-basicauth
