apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gabinheylen/k8s-gitops.git'
    targetRevision: main
    path: 'longhorn'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
