apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  WORDPRESS_DB_HOST: "wordpress-mysql:3306"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_HOME', 'https://wp-test.ga-nan.ovh');
    define('WP_SITEURL', 'https://wp-test.ga-nan.ovh');
