apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-init-config
  namespace: homeassistant
data:
  configuration.yaml: |
    homeassistant:
      name: Home
      country: FR
      time_zone: Europe/Paris

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 192.168.0.0/16

    default_config:
