apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik-public
spec:
  defaultCertificate:
    secretName: vaultwarden-tls
---
apiVersion: traefik.io/v1alpha1
kind: CertificateResolver
metadata:
  name: letsencrypt
  namespace: traefik-public
spec:
  acme:
    email: gabin0406heylen@gmail.com
    storage: /data/acme.json
    httpChallenge:
      entryPoint: web
